language: java
sudo: required
install: true

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

services:
  - docker

addons:
  sonarcloud:
    organization: "heckenmann-github"
    token:
      secure: "36CKG7Jy65aN4sSgGAjH04Hg7zyHbVpOjoSN9zLOJpI0wJBuzN5pEd9l2xsWjVLu6testLqIwtc4NXtm1VEiKlcol7VhuVmiZauKvtiPuVthMDQxUX9wiMSK3L30k+y7+s9FHV33zZey9zVtmxGHUQlGjf228hmmq9+wiLvXMPiQ7ml9L/ZwFKU7XgOS9ZQegFtKej45GTvx38jTcJQJhF7/vFim2LYxx3esxaMNXX/tVIhXisO24z0Uu/BAPS4yGwMx90FzYLHKPLJrjQ0dHZUjstiYTb49M0blvBjmbnF9rkb8lKhY9HKRmf2njWTf6/0R6TbIwmZO7DPKT4Zt/hIoM+VhUerMY4QbFupGrk3zuTqZGS4NifDAi7NMmfek4IHnuZv2IfiGWBArjZw/eMEp4Uy+HQOlqxM1ApjRmAle+wcwS1Y+jZpRalPm4Tn22ifOOyME1Ogz5+HvnIHpL/i6l0Z68n56h23WGwJtzf371vumF7leh3ebB5UtI8zqGHitTR4SHEx9JyJ6R6rNeAnSZdTZRnBGRb+UiTEYRbMvpLYWTNLq8Sf8KiM+W/NHaYo6kQp/dwlJY10WH+Q/hX1wnnac/Fd/PLLIVygdLR3o9FMM9yzYB7ySIZ9RhTtpUbpeASkMWAtEcRtCASs12R7rnALDYIEypTUN2+hKmkI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true
  - mvn test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
